# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QSizePolicy, QVBoxLayout, QHBoxLayout
from PyQt5.QtWidgets import QFrame, QLineEdit, QLabel, QSpacerItem, QPushButton
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtCore import QSize

import home


class ClientWidget(QFrame):
    def __init__(self, client: home.Client):
        super().__init__()

        self.client = client

        self.setObjectName("ClientWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setStyleSheet("QPushButton{\n"
                           "    width: 60px;\n"
                           "    height: 60px;\n"
                           "}")
        self.setFrameShape(QFrame.StyledPanel)
        self.setFrameShadow(QFrame.Raised)
        
        # Информация о клиенте
        self.nameLineEdit = QLineEdit(self)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLineEdit.setText(self.client.get_name())

        self.typeLabel = QLabel(self)
        self.typeLabel.setObjectName("typeLabel")
        self.typeLabel.setText(self.client.get_kind())

        self.idLabel = QLabel(self)
        self.idLabel.setObjectName("idLabel")
        self.idLabel.setText(self.client.get_id())
        
        # Проствранство с информацией о клиенте
        self.infoVLay = QVBoxLayout()
        self.infoVLay.setContentsMargins(0, -1, -1, -1)
        self.infoVLay.setObjectName("infoVLay")

        self.infoVLay.addWidget(self.nameLineEdit)
        self.infoVLay.addWidget(self.typeLabel)
        self.infoVLay.addWidget(self.idLabel)

        self.line = QFrame(self)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")

        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.line_2 = QFrame(self)
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        # Кнопка открытия настроек клиента
        self.infoButton = QPushButton(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoButton.sizePolicy().hasHeightForWidth())
        self.infoButton.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addPixmap(QPixmap("../../../../../Downloads/right-arrows.png"), QIcon.Normal, QIcon.Off)
        self.infoButton.setIcon(icon)
        self.infoButton.setIconSize(QSize(60, 60))
        self.infoButton.setObjectName("infoButton")


        # Основное пространство
        self.clientHLay = QHBoxLayout()
        self.clientHLay.setObjectName("clientHLay")

        self.clientHLay.addLayout(self.infoVLay)
        self.clientHLay.addWidget(self.line)
        self.clientHLay.addItem(spacerItem)
        self.clientHLay.addWidget(self.line_2)
        self.clientHLay.addWidget(self.infoButton)

        self.setLayout(self.clientHLay)

        self.show()