# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rooms.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import logging


class RoomsMenu(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.rooms = ["All", "MyRoom", "Kitchen", "New"]

        self.logger = logging.getLogger("ROOMSMENU")

        self.setObjectName("RoomsWidget")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.setStyleSheet("QLabel{\n"
                            "    font-size: 16px;\n"
                            "}\n"
                            "QLabel#mainLabel{\n"
                            "    font-size: 25px;\n"
                            "}\n"
                            "QComboBox{\n"
                            "    font-size: 20px\n"
                            "}\n"
                            "QLineEdit{\n"
                            "    font-size: 20px;\n"
                            "}\n"
                            "QPushButton{\n"
                            "    width: 70px;\n"
                            "    height: 70px;\n"
                            "    margin-right: 5px;\n"
                            "}\n"
                            "QFrame#clientFrame{\n"
                            "    border: 1px solid;\n"
                            "}")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        # Название окна
        self.mainLabel = QtWidgets.QLabel(self)
        self.mainLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainLabel.setScaledContents(False)
        self.mainLabel.setObjectName("mainLabel")
        self.mainLabel.setText("Rooms")

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        # Пространство для объекта название окна
        self.labelHLay = QtWidgets.QHBoxLayout()
        self.labelHLay.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.labelHLay.setObjectName("labelHLay")
        self.labelHLay.addItem(spacerItem)
        self.labelHLay.addWidget(self.mainLabel)
        self.labelHLay.addItem(spacerItem1)

        # Прямая разделяющая заголовок окна и меню комнат
        self.line = QtWidgets.QFrame(self)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # Список комнат с возможностью выбора комнаты
        self.RoomsBox = QtWidgets.QComboBox(self)
        self.RoomsBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoomsBox.sizePolicy().hasHeightForWidth())
        self.RoomsBox.setSizePolicy(sizePolicy)
        self.RoomsBox.setMaximumSize(QtCore.QSize(200, 100))
        self.RoomsBox.setObjectName("RoomsBox")
        self.RoomsBox.addItems(self.rooms)

        # Простаранство для объекта выбора комнат
        self.RoomsLayout = QtWidgets.QHBoxLayout()
        self.RoomsLayout.setObjectName("RoomsLayout")
        self.RoomsLayout.addWidget(self.RoomsBox)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

        # Пространство клиентов и возможностью прокрутки
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 764, 691))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_6.addItem(spacerItem2)

        self.RoomScrollArea = QtWidgets.QScrollArea(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoomScrollArea.sizePolicy().hasHeightForWidth())
        self.RoomScrollArea.setSizePolicy(sizePolicy)
        self.RoomScrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.RoomScrollArea.setMouseTracking(True)
        self.RoomScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.RoomScrollArea.setWidgetResizable(True)
        self.RoomScrollArea.setObjectName("RoomScrollArea")
        self.RoomScrollArea.setWidget(self.scrollAreaWidgetContents_2)

        # Основоное простанство для всех остальных простанств
        self.mainVLay = QtWidgets.QVBoxLayout()
        self.mainVLay.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainVLay.setObjectName("mainVLay")
        self.mainVLay.addLayout(self.labelHLay)
        self.mainVLay.addWidget(self.line)
        self.mainVLay.addLayout(self.RoomsLayout)
        self.mainVLay.addWidget(self.RoomScrollArea)

        self.setLayout(self.mainVLay)
        
        self.show()

    
    
    def delete_room(self, room_name): # Удалить комнату по имени
        try:
            self.rooms.remove(room_name)
        except ValueError:
            self.logger.warning(room_name + " is missing from the list of rooms")
    
    def add_room(self, room_name): # Добавить комнату
        if (room_name == ""):
            self.logger.warning("room_name is empty")
        else:
            self.rooms.append(room_name)
