# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rooms.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roomsWidget(object):
    def setupUi(self, roomsWidget):
        roomsWidget.setObjectName("roomsWidget")
        roomsWidget.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(roomsWidget.sizePolicy().hasHeightForWidth())
        roomsWidget.setSizePolicy(sizePolicy)
        roomsWidget.setStyleSheet("QLabel{\n"
"    font-size: 16px;\n"
"}\n"
"QLabel#MainLabel{\n"
"    font-size: 25px;\n"
"}\n"
"QComboBox{\n"
"    font-size: 20px\n"
"}\n"
"QLineEdit{\n"
"    font-size: 20px;\n"
"}\n"
"QPushButton{\n"
"    width: 70px;\n"
"    height: 70px;\n"
"    margin-right: 5px;\n"
"}\n"
"QFrame#clientFrame{\n"
"    border: 1px solid;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(roomsWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainVLay = QtWidgets.QVBoxLayout()
        self.mainVLay.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainVLay.setObjectName("mainVLay")
        self.labelHLay = QtWidgets.QHBoxLayout()
        self.labelHLay.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.labelHLay.setObjectName("labelHLay")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.labelHLay.addItem(spacerItem)
        self.MainLabel = QtWidgets.QLabel(roomsWidget)
        self.MainLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainLabel.setScaledContents(False)
        self.MainLabel.setObjectName("MainLabel")
        self.labelHLay.addWidget(self.MainLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.labelHLay.addItem(spacerItem1)
        self.mainVLay.addLayout(self.labelHLay)
        self.line = QtWidgets.QFrame(roomsWidget)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainVLay.addWidget(self.line)
        self.RoomsLayout = QtWidgets.QHBoxLayout()
        self.RoomsLayout.setObjectName("RoomsLayout")
        self.RoomsBox = QtWidgets.QComboBox(roomsWidget)
        self.RoomsBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoomsBox.sizePolicy().hasHeightForWidth())
        self.RoomsBox.setSizePolicy(sizePolicy)
        self.RoomsBox.setMaximumSize(QtCore.QSize(200, 100))
        self.RoomsBox.setObjectName("RoomsBox")
        self.RoomsLayout.addWidget(self.RoomsBox)
        self.mainVLay.addLayout(self.RoomsLayout)
        self.RoomScrollArea = QtWidgets.QScrollArea(roomsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoomScrollArea.sizePolicy().hasHeightForWidth())
        self.RoomScrollArea.setSizePolicy(sizePolicy)
        self.RoomScrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.RoomScrollArea.setMouseTracking(True)
        self.RoomScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.RoomScrollArea.setWidgetResizable(True)
        self.RoomScrollArea.setObjectName("RoomScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 764, 691))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.RoomScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.mainVLay.addWidget(self.RoomScrollArea)
        self.horizontalLayout.addLayout(self.mainVLay)

        self.retranslateUi(roomsWidget)
        QtCore.QMetaObject.connectSlotsByName(roomsWidget)

    def retranslateUi(self, roomsWidget):
        _translate = QtCore.QCoreApplication.translate
        roomsWidget.setWindowTitle(_translate("roomsWidget", "Form"))
        self.MainLabel.setText(_translate("roomsWidget", "Rooms"))
